nodeLinker: node-modules

npmScopes:
  plitzi:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.pkg.github.com/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
